version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    # see also: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-circleci
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          # See: https://circleci.com/docs/2.0/collect-test-data/#jest
          command: npm run test-ci
          environment:
            JEST_JUNIT_OUTPUT: 'test-results/jest/js-test-results.xml'
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-results/
